name: CI

on: pull_request

jobs:
 continuous-inegration:
  runs-on: ubuntu-latest
  defaults:
    run: 
      working-directory: Front
      
  steps:
      - uses: actions/checkout@v4

      - name: Instalar dependÃªncias
        run: npm install

      - name: Rodar build
        run: npm run build
