name: CI

on: pull_request

jobs:
 continuous-inegration:
  runs-on: ubuntu-latest
	 
  defaults:
    run: 
      working-directory: Front
  steps:
   - uses: actions/checkout@v3
   - name: Using Node.js
     uses: actions/setup-node@v2
     with:
       node-version: 18.x
   - name: run install,build e test
     run: |
      npm install
      npm run build
      npm run test
